[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
trust_rent = "J5KBZXVNtTEA1YWWztgk1MGcW9yzc8344FJvYxojDbsU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/brandonrobb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
